# Generated by Django 4.1.7 on 2023-04-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mrec', models.IntegerField()),
                ('dt', models.DateTimeField(default='1970-01-01 00:00:00')),
            ],
        ),
    ]
